### PR TITLE
Fix `enterXXX` for alternative labels

### LINKED ISSUE #12: `enter_XXX` for alternative labels are not invoked
`enter_XXX` for alternative labels are not invoked, while `enter_every_rule` and `enter_XXX` for rules are called.

Given the grammar:

```antlr
grammar Test;

prog
    : ident EOF
    ;

ident
    : 'tohka'   # Tohka
    ;
```

and the input `tohka`, the following program 
```rust
#![feature(try_blocks)]
#![feature(exclusive_range_pattern)]

#[macro_use]
extern crate lazy_static;

#[allow(warnings)]
pub mod testlexer;
#[allow(warnings)]
pub mod testlistener;
#[allow(warnings)]
pub mod testparser;

use testlexer::*;
use testlistener::*;
use testparser::*;

use antlr_rust::common_token_stream::CommonTokenStream;
use antlr_rust::input_stream::InputStream;
use antlr_rust::tree::ParseTreeListener;

struct Listener;

impl ParseTreeListener for Listener {}

impl TestListener for Listener {
    fn enter_prog(&mut self, _ctx: &ProgContext) {
        println!("enter prog");
    }

    fn exit_prog(&mut self, _ctx: &ProgContext) {
        println!("exit prog");
    }

    fn enter_Tohka(&mut self, _ctx: &TohkaContext) {
        println!("enter Tohka");
    }

    fn exit_Tohka(&mut self, _ctx: &TohkaContext) {
        println!("exit Tohka");
    }
}

fn main() {
    let lexer = TestLexer::new(Box::new(InputStream::new("tohka".into())));
    let token_source = CommonTokenStream::new(lexer);
    let mut parser = TestParser::new(Box::new(token_source));
    let listener = Listener;

    let id = parser.add_parse_listener(Box::new(listener));
    parser.prog().expect("failed to parse");

    let _ = parser.remove_parse_listener(id);
}
```
prints

```
enter prog
exit Tohka
exit prog
```

which should be like the following:

```
enter prog
enter Tohka
exit Tohka
exit prog
```

### PR DESCRIPTION
**Pull request by 3c1u**
This will fix #12.

### CODE REVIEW

**Comment by rrevenantt** [comment]
Thanks, apparently Java target has the same issue https://github.com/antlr/antlr4/issues/802 that has not been fixed for 5 years, which makes me think that fix can't be as simple as you suggest, although at first glance I don't see any problem with it. So i will take some more time to find out if there is anything wrong.

**Comment by 3c1u** [comment]
I checked most targets (Java, C#, C++, JavaScript, Go) and their runtime seem to have the identical code on `enterRule` and `enterOuterAlt`, and thus, they won't invoke `enter_rule` for alt labels.

Interestingly, Swift target goes otherwise. It triggers enter events in `enterOuterAlt`, not in `enterRule` (see https://github.com/antlr/antlr4/blob/master/runtime/Swift/Sources/Antlr4/Parser.swift#L637). It emits `enter_rule` event for alternative labels properly.

**Comment by rrevenantt** [comment]
Hmm..., triggering all enter events in `enterOuterAlt` instead of `enterRule` looks more logical. Also in this case triggering in `enterRecursionRule` will be also redundant (although, Swift target still do it, i am quite sure that it is a bug).
Would you mind changing PR this way?

**Comment by 3c1u** [comment]
Changed. I made a PR for other targets (https://github.com/antlr/antlr4/pull/2910) and it passed tests (on Travis CI; AppVeyor build failed because "Build execution time has reached the maximum allowed time for your plan (60 minutes)."), so it seems to be okay.

**Comment by rrevenantt** [comment]
Perhaps I wasn't clear. You also need to remove `trigger_enter_rule_event` from `enter_recursive_rule` because it replaces `enter_rule` for left recursive rules. I believe same can be applied to other target as well.

**Comment by 3c1u** [comment]
I tested with a grammar with recursion, and it was surely redundant. I'll fix the PR for other targets then.

**Pull request merged**
