### PR TITLE
Remove unused raw feature

### LINKED ISSUE #25: antlr does not compile due to depricated raw feature
If one uses nightly <=1.53, this crate compiles and works as expected.  However, once the switch is made to 1.55, it no longer works and gives the error

```
 error[E0635]: unknown feature `raw`
 --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/antlr-rust-0.2.0/src/lib.rs:4:12
  |
4 | #![feature(raw)]
  | 
```
I am importing this crate through
```
antlr-rust = "=0.2"
```
as mentioned in the readme.

I believe the error is because as mentioned [here](https://doc.rust-lang.org/std/raw/index.html) in the Rust documentation, the raw feature has been deprecated.  Can this be updated so antlr doesn't use the raw feature?

### PR DESCRIPTION
**Pull request by newca12**
Fix #25

### CODE REVIEW

**Comment by liamrosenfeld** [comment]
Can this get merged in? This one line prevents the crate from compiling on current Rust versions.

**Comment by newca12** [comment]
This is already fixed in branch v0.3 https://github.com/rrevenantt/antlr4rust/tree/v0.3 your best bet is to build it yourself or convince the author to release it. The main arguments are that the current release is not usable and v0.3 is actually in very good shape. I used it for https://github.com/newca12/the-definitive-antlr4-reference-rs with no major issue.

**Comment by liamrosenfeld** [comment]
@newca12, thank you for the advice. I will give v0.3 a try. Where is the antlr generation jar for v0.3? I've looked around for it but have not found it.

**Comment by newca12** [comment]
You just have to follow the instructions in the REAME to build the jar.
Of course you will need first to set the submodule repository to the v0.3 branch.

**Pull request closed without merging**
